### ISSUE TITLE
"Proper" nested transactions

### ISSUE THREAD

**Issue by ypercube** [vitaly-t/pg-promise#134]
The readme has:

> Proper support for nested transactions means that the result of a successful sub-transaction isn't rolled back when its parent transaction is rolled back.

What does "proper" mean above and according to whom? Which DBMS has implemented nested transactions this way?

Perhaps the author of this paragraph had Autonomous Transactions in mind and not Nested Transactions?

**Comment by vitaly-t** [comment]
Yes, that was about Autonomous Transactions.

Also, worth pointing out, that PostgreSQL does not support nested `BEGIN`->`COMMIT`, one has to use save points within the to-level `BEGIN`->`COMMIT`, which `pg-promise` does automatically.

**Comment by ypercube** [comment]
Thank you.

I didn't intend to submit this a bug, maybe just a glitch in the docs, but I couldn't add the "doc" label.

I think only Oracle and DB2 has true autonomous transactions. SQL Server, no: [Connect titem](https://connect.microsoft.com/SQLServer/feedback/details/296870/add-support-for-autonomous-transactions)

**Comment by ypercube** [comment]
As I found our from a SQL Server expert, SQL Server uses them internally (for example in sequence/identity columns and for page splits not to roll back) but they are not exposed to the users.

**Comment by vitaly-t** [comment]
I should say that when I used the word "proper", I meant that PostgreSQL does not support nested `BEGIN`->`COMMIT`, only save points below the the top-level transactions.

When I started working on it initially, it all seemed quite awkward to automate, because save points require automatically generated names, but I got it all working eventually :)
