### ISSUE TITLE
Character `-` in named parameters.

### ISSUE THREAD

**Issue by boromisp** [vitaly-t/pg-promise#137]
Hi,

Is there any reason not to support kebab-cased named parameters? It would make my code much simpler, if I wouldn't have to camelCase every property in the params object, and in the query string.

The only change required to make it work would be adding a single character at https://github.com/vitaly-t/pg-promise/blob/dadde76f9ae02374bb827e5301ac7ac9901fb210/lib/formatting.js#L116.

Thanks.

**Comment by vitaly-t** [comment]
There are 2 standards for property names in JavaScript:

* variable notation
* string notation

The one we are using is the variable notation, which includes everything that defines a valid variable in JavaScript. Symbol `-` isn't part of valid JavaScript name.

The string notation supports just about all possible characters. It is not used because it eliminates the possibility to extend names via formatting modifiers and casting.

For example, all formatting modifiers that we support, as per method [as.format](http://vitaly-t.github.io/pg-promise/formatting.html): `^`, `~`, `#`, `:csv`, `:json`, `name`, `raw`, `:value`.

What makes it even worse, defining a variable name with containers such as these: `${}`, `$()`, etc wouldn't be accurate enough also.

So, the full string notation for properties is out of the question.

There are a few solutions to your problem. First of all, you do not need to camel case the results of all queries. You can use event [receive](http://vitaly-t.github.io/pg-promise/global.html#event:receive) to do this automatically for everything, as shown in the example there.

Secondly, there is powerful new feature - [helpers namespace](http://vitaly-t.github.io/pg-promise/helpers.html), which is currently still in Alpha, but it allows automatic approach to generating queries for any column names.

**Comment by boromisp** [comment]
I see your point.
I ended up doing something like this:

```javascript
// field could be eg. 'arrived-timestamp'
const paramName = field.replace(/[^a-zA-Z0-9\$_]/g, '_'); 
// field isn't user input, so this should be safe
query += ` WHERE table.column=$<${paramName}>`;
params[paramName] = value;
```

The helpers namespace looks interesting, but for my use case not really applicable.

**Comment by vitaly-t** [comment]
But you would have to do that manually. Why not simply use the code shown in the `receive` event?

**Comment by boromisp** [comment]
Because the receive event happens after the query.

What would I need, is preprocessing before query parameter name parsing. I could possibly do that in the 'query' event handler, but I rather use supported parameter naming in the first place.

I could solve this much cleaner, then I first thought it would be possible, so this turned out to be a non-issue.
