### ISSUE TITLE
Over 9999 numbered params

### ISSUE THREAD

**Issue by schnie** [vitaly-t/pg-promise#143]
Hey @vitaly-t!  I'm running into an issue where a SQL statement has 10000+ params.  It ends up leaving some numeric values out of place after it does some regex replacement in the `formatting` module.  This results in some weird errors like `syntax error at or near "0"`, where there is a dangling zero in the final string where it replaced `(1000)` with the appropriate value but left a dangling 0 (the last digit of 10000).  Is there a reason to limit it to this?  It's specifically happening where I'm doing a bulk insert with a ton of rows.  This will eventually be replaced with a `COPY` command but I just wanted to check if there was a real reason to limit this?  I'm thinking its this line: https://github.com/vitaly-t/pg-promise/blob/5671a08b300a3c3c549a8f56d232346108e77318/lib/formatting.js#L134

Thanks!

**Comment by vitaly-t** [comment]
The limitation is on the number of columns in a single row, not on the number of params, because you are not supposed to use it in that way, and if you are using it that way, that's a not a good approach at all.

As I understand, you are trying to do a bulk insert. Check out out the latest question about that: [Multi-row insert with pg-promise](http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise)

That will guide you how to do it properly.

**Comment by vitaly-t** [comment]
I take it the issue has been resolved? ;)

**Comment by TazmanianDI** [comment]
@vitaly-t I think I may have hit this problem as well except for me it's on a large IN clause with a SELECT query. The alternatives for doing large INSERTs and UPDATEs don't apply here so I'm not really sure what to do.

I have a query that basically looks like this:

```
SELECT * FROM "myTable" WHERE ("colOne", "colTwo", "colThree") IN (($1,$2,$3),($4,$5,$6),...,($820,$821,$822))
```

And the array I'm passing to the database call has 822 elements in it. But I get the `there is no parameter $10000` error out of this. I don't even have 10000 items in the array. I'm not really sure what to do about this. I could probably split the query into smaller pieces but that seems less than desirable.

**Comment by vitaly-t** [comment]
@TazmanianDI it is a related problem, in a sense that you are also misusing the query-formatting engine. But the way you do it is also different.

You should never have things like this: `IN (($1,$2,$3),($4,$5,$6),...,`, that's the wrong query formatting approach.

Typically, when one has so many parameters, you are trying to use sttaic formatting instead of the dynamic one, i.e. use `SELECT` as the source for the parameters, rather than pull so many records from the memory.

And in situations where you do have so many parameters in memory, have each object support [Custom Type Formatting], and then inject an array of those using the `:csv` filter.

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting

**Comment by TazmanianDI** [comment]
The custom format would reduce the number of parameters I've got by a third but that's just a slight shift in the amount of data I've got to process. I think I might like doing that anyway as flattening out the parameters is a bit of an annoyance in our code.

This is a bit of an edge case for us; this occurs during some rare "first time" data initializations so it's not like this is a regular query (I'd be an idiot to frequently execute a query with 125k parameters ;-). Will the custom format do the right thing when used as a compound value in an IN clause? I.e., the query does need the extra parens around each value:

```
IN ((val1, val2), (val3, value4))
```

The values required in the query really are being computed in memory (it's looking for sets of missing data). I'm not sure I understand your recommendation "SELECT as the source for the parameters". If you mean use a sub-query to get the parameters, that's not so easy to do in our usage as determining what needs to be queried for is complicated.

I think I am going to try and rework this anyway as 125k really is quite a lot. Maybe I can break down the data into ranges instead of discreet points. But is there a reason you put `{0,3}` in the query replace regexp? Is there some specific limitation you're avoiding by putting the limit in there. I understand it's not smart to query with 125k params but seems like the library should allow me to be stupid if it's something Postgres can actually live with.

I do appreciate the quick responses from you; you're pretty good about that :-).

**Comment by vitaly-t** [comment]
> The custom format would reduce the number of parameters I've got by a third

You misunderstand, it would reduce the number of formatting parameters to just the list of properties. And in your example that's just 3.

**Comment by TazmanianDI** [comment]
Oh, so in 
```
db.any('...IN ($1:csv)', [a1, a2, ...]);
```
`$1` refers to the entire array? `[a1, a2, ...]`? What if I had some additional values that aren't part of that IN clause? Would it be 
```
db.any('...IN ($2:csv) AND col = $1', [b1, [a1, a2, ...]]);
```

**Comment by vitaly-t** [comment]
> $1 refers to the entire array?

Yes, precisely.

> What if I had some additional values that aren't part of that IN clause? Would it be

Of course!

**Comment by vitaly-t** [comment]
Pardon, I've made a little mistake in the example...

You need to pass it in like this:

```js
db.any('....IN($1) WHERE something = $2', [[a1, a2, ...], 123])
```
or via Named Parameters:
```js
db.any('....IN(${names:csv}) WHERE something = ${id}', {
  names: [a1, a2, ...],
  id: 123
})
```

**Comment by TazmanianDI** [comment]
I hope I'm not doing something stupid but there's something not quite right here: 

```
function MyType(val1, val2) {
  this.val1 = val1;
  this.val2 = val2;
  this._rawDBType = true;

  this.formatDBType = function() {
    return pgPromise.as.format('${val1}, ${val2}', this);
  }
}

const values = [
  new MyType('00000000-0000-0000-0000-000000000000', '00000000-0000-0000-0000-000000000000'),
];

const sql = 'SELECT * FROM "myTable" WHERE ("val1", "val2") IN ($1:csv)';
database.any(sql, [values])
```

Spits out this:

```
RangeError: Maximum call stack size exceeded
    at MyType.formatDBType (.\test\sandbox.js:30:25)
    at resolveFunc (.\node_modules\pg-promise\lib\formatting.js:205:29)
    at $formatQuery (.\node_modules\pg-promise\lib\formatting.js:234:40)
    at Object.format (.\node_modules\pg-promise\lib\formatting.js:686:16)
    at MyType.formatDBType (.\test\sandbox.js:30:25)
    at resolveFunc (.\node_modules\pg-promise\lib\formatting.js:205:29)
    at $formatQuery (.\node_modules\pg-promise\lib\formatting.js:234:40)
    at Object.format (.\node_modules\pg-promise\lib\formatting.js:686:16)
    at MyType.formatDBType (.\test\sandbox.js:30:25)
    at resolveFunc (.\node_modules\pg-promise\lib\formatting.js:205:29)
```

The `formatDBType` seems to be getting stuck in a loop.

**Comment by vitaly-t** [comment]
Yes, I can see where the problem comes form... replace this:
```js
return pgPromise.as.format('${val1}, ${val2}', this);
```
with this:
```js
return pgPromise.as.format('$1, $2', [this.val1, this.val2]);
```
...to avoid recursive custom-formatting call.

**Comment by TazmanianDI** [comment]
Okay, that does seem to work with one more tweak. I did have to put parens around the values in `formatDBType` in order to get them to appear properly as a composite IN clause. That does mean this formatting does need to know something about how it's used (specifically being used in an IN clause). Are there other circumstances you had in mind for supporting this kind of formatting where the parens would actually be bad and this formatting function wouldn't work (I guess I'd have to create a new type for that unless I can specify the formatters *per request*).

```
return pgPromise.as.format('($1, $2)', [this.val1, this.val2]);
```

**Comment by vitaly-t** [comment]
I don't understand why you had to put parenthesis inside `formatDBType`. When we use `_rawDBType = true`, we say exactly the opposite, i.e. setting it to false or just skipping altogether would result in the output string being wrapped in parenthesis automatically.

**Comment by vitaly-t** [comment]
If you use it as `($1)` as was in the code example earlier, then you wouldn't need adding any parenthesis there ;)

**Comment by TazmanianDI** [comment]
You might be missing that I'm executing a query with an IN clause using composite values (i.e. more than one column). If I leave out the parens from the formatting function:

```
function MyType(val1, val2) {
  this.val1 = val1;
  this.val2 = val2;
  this._rawDBType = true;

  this.formatDBType = function() {
    return pgPromise.as.format('$1, $2', [this.val1, this.val2]);
  }
}

const values = [
  new MyType('1', '2'),
  new MyType('3', '4'),
];

const sql = 'SELECT * FROM "myTable" WHERE ("col1", "col2") IN ($1:csv)';
database.any(sql, [values]);
```

This generates the query: 

```
SELECT * FROM "myTable" WHERE ("col1", "col2") IN ('1', '2','3', '4')
```

The parens are missing inside the IN clause. This query should be

```
SELECT * FROM "myTable" WHERE ("col1", "col2") IN (('1', '2'),('3', '4'))
```

**Comment by vitaly-t** [comment]
Gotcha, you're right! :wink:

**Comment by vitaly-t** [comment]
[Version 6.0.16](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.0.16) of the library increased the limit to 99,999.

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
