### ISSUE TITLE
Named parameters with prepared statements

### ISSUE THREAD

**Issue by ghusse** [vitaly-t/pg-promise#145]
Hello,

Is it possible to use named parameters in prepared statements?

I tried to use the combination of the two, but got this error : `PreparedStatementError: Property 'values' must be an array or null/undefined.`

**Comment by vitaly-t** [comment]
It is not possible, because Prepared Statements by definition are formatted by the database server only, while Named Parameters are part of this library's query formatting.

**Comment by ghusse** [comment]
OK, I understand.

I suppose it would be possible for the JS code to transform queries with named parameters to a query with indexed parameters. But for now it's not the case.

**Comment by vitaly-t** [comment]
This was discussed in the past. It cannot, or rather shouldn't be done, because Named Parameters in this library support advanced syntax of type modifiers that cannot be translated into simple variables. Translating just a subset of Named Parameters into regular variables would only create more confusion. Therefore, it is not going to happen.
