### ISSUE TITLE
TypeScript definition for pg.Client.on

### ISSUE THREAD

**Issue by teledemic** [vitaly-t/pg-promise#180]
Currently missing - would help avoid kludgy "any" defines when doing listen / notify as in:
https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#listen--notify

**Comment by vitaly-t** [comment]
That's because this library uses its own, simplified TypeScript ambient declaration for `pg`, as I couldn't find any good one when I was adding it.

To my knowledge, it doesn't exist. Have you seen any good one? By good one, I mean a complete one. They all seem very incomplete, that's why I wrote one myself.

**Comment by goenning** [comment]
@vitaly-t Have you tried https://github.com/typed-typings/typed-pg? I'm trying to keep it up to date as much as possible.

**Comment by vitaly-t** [comment]
@goenning thank you, I saw it earlier. The first difference I noticed - the following types missing altogether: `IColumn` and `IResult`.

Also, I tired to keep naming the same, only adding `I` in front. You changed some of them.

**Comment by vitaly-t** [comment]
This has been addressed in [v.5.1.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.1.4).
