### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by emilioplatzer** [vitaly-t/pg-promise#2]
Do you think about include tests? 

Can I help you with this?

If you start I try to help

**Comment by vitaly-t** [comment]
I did yes, but thinking about it was as far as I got.

For one thing, I haven't done any proper testing using Karma or similar, so I don't have enough experience. But surely, I'd figure it out quick once I get started.

For another - I always thought that testing database frameworks is a major pain, because you need a database to do it properly; otherwise - what is it worth?

I started with the first draft only 2 days ago, and since then made 15 releases, tons of documentation, and continue spending all my time on it.

Today I added my first milestone to it to make some breaking changes to do proper support for using multiple databases. And right now, just 3 hours later I have already finished it - see the code in branch v.0.2. It all seems to be working, i'm just gonna give it a bit more testing and update documentation, and i'm done. It turned out to be a big rewrite, though doesn't affect the usage cases much.

Anyhow, I really appreciate you offering your help with the test. I think that simply forking it out for yourself is the right way to go. The only hold-up, i'd say, I've just made huge changes, so writing the actual tests wouldn't be of much benefit, till I do another release shortly, but setting up the test frameworks for now - sure thing!

Right now, I would start it myself, after I finalize the ongoing changes. Feel free throwing in any suggestions in the meantime or forking it out to add a test framework ;)

**Comment by emilioplatzer** [comment]
Thanks for the fast answer. 

I apologize for my poor English (I'm Spanish skpeaker). 

For pg-promise I can wait the next version (0.2). I'm very interested in this module. I thought that have something like queryResult is a great feature. 

I have some skills in testing and coverage. I start writing Node modules recently, the last ones with 100% test coverage. 

I'm using Mocha, Travis-CI and coveralls.io 

Thanks

Emilio

**Comment by vitaly-t** [comment]
Sound we just might make a good testing team :) let me get back to you once I've finished the current massive changes for 0.2.0 ;)

**Comment by vitaly-t** [comment]
As an update... the code seems to be finished and working, and the documentation is also up-to-date.

I'm going to merge this branch v.0.2 into the master branch tomorrow, perhaps improve the documentation and then release 0.2.0, at which point it will be possible to do some tests integration ;)

**Comment by emilioplatzer** [comment]
if you let me make a suggestion: 
 * you can evaluate to change the C-style form of passing options (queryResult.none | queryResult.many) with JS-object-style form {none:true, manu:true} 
 * you can evaluate to prepare the module to have full functionality in the future. In the mean time thats means:
    * you should permit pass parameters to the query function:

```js
    query('select country from countrys where population>$1' , [10000]).then(...
```

**Comment by vitaly-t** [comment]
@emilioplatzer,

The new version just has been released, so you can fork it and start on the tests, if you want ;)

* I opted for the C-style because I have 3 flags with all the combinations. I'm not sure if it would look as readable in any other form. If you think it would - please give me a complete example, so I can understand it.

* Passing parameters isn't part of PG or Promise, so you are talking about just extra functionality for the library. I've seen a number of packages that do just that - format parameters, so I didn't want to get into that, focusing just on the core functionality between PG and Promise, or at least for now :)
Also, I do process parameters when calling a function or procedure ;)

* I think that adding automated testing is much more important now than extending the library with new functionality ;)

**Comment by vitaly-t** [comment]
UPDATE:

I've done enough updates and even released for today, I think :)

What you may find interesting is section <b>Understanding the query result</b>, which explains in detail how Query Result works. So, if you still want to come back with a suggestion about changing it, that explanation should help ;)

**Comment by emilioplatzer** [comment]
I'm happy with your quick responses. Thanks. 

I like the feature of control the number of records in the result (none, one and many). Buy I need the parameter of client.query that pg have (at the moment I'm using parameters in my queries). 

I'll try with pg-bluebird. May be I add a filter that controls de recordCount. Something like: 

```js
client.query("select $1::integer", [1]).then(pgControls.OnlyOne).then(function(data){
  // do something usefull with data!
});
```

**Comment by vitaly-t** [comment]
Oh my, that bluebird promise implementation, makes you wonder: 700k of monthly downloads for promise, 600k monthly downloads for bluebird, makes it tough to choose which one to use :)

Not that I have anything against blue birds, though it is a strange name, I prefer promise as the name :)

Thank you for pointing out at that pg-bluebird package, I will have to look through the code. Pity they do not have any demo for parameters usage to understand it better how it works.

**Comment by emilioplatzer** [comment]
It's a pqlib feature. It's referred in pg readme.md in client.query example. 

Try this:
```js
var pg = new PGBlueBird();
pg.connect(config.db).then(function(conn){
    console.log('connected!',connection);
    return conn.client.query("SELECT 2 + $1", [5]);
}).then(function(data){
    console.log('data recived',data);
});
```

**Comment by vitaly-t** [comment]
For now my question is -is this formatting thing handled by pglib or is it just a pg package feature?

I mean, i'm trying to understand just how important it is. Is there a scenario where you could pass a parameter through PG but not through my library? I mean, after all, I amk accepting a generic query syntax, so you are free to format it any in any that you want.

Let me know what you think ;)

Cheers!

**Comment by vitaly-t** [comment]
And while I'm still thinking about the value formatting, I did a fix in it, plus added as.csv, as a pre-emptive to our discussion about value formatting.

Now one can call it like this:
```javascript
db.none("update users(name, active, updated) values({0})".format(pgp.as.csv([
"John O'Dwyer", true, new Date()
])));
```
I know this isn't an answer to what we are discussing, it's just a small step in that direction, in a generic way.

When we call:
```javascript
pgp.as.csv(["John O'Dwyer", true, new Date()]);
```
were are getting this:
```javascript
'John O''Dwyer',TRUE,'Fri, 06 Mar 2015 21:40:45 GMT'
```
Note how a single quote in text was fixed, boolean and Date properly represented. So, it is a good helper, I believe ;)

**Comment by vitaly-t** [comment]
Ok, after having given it some consideration, I have added support for parameter formatting, so now all query functions can called like this:
```javascript
db.many('select * from users where name like $1', '%vit');
db.many(select * from audit where updated > $1 and entity = $2', [new Date(), 'test']);
```
Because of this, I had to make a breaking change in the function usage, so it is now:
```javascript
db.func('funcName', queryResult.one, [true, 'hello'])
```
i.e. we have to pass the queryResult as the second parameter and then the values, as it is now consistent with method <b>query</b>.

I haven't updated the documentation to reflect the change just yet, but will soon.

**Comment by vitaly-t** [comment]
Since you haven't replied since Friday, and I have rewrote 80% of the library code over the weekend, updated the document and published the new release, which includes both value formatting that you asked for and much-much more.

So, I'm closing this issue, since it has become a topic lost in conversation. If you still want to contribute with a testing framework - feel free to fork it out. I'm not planning to make the same huge changes any more :)

**Comment by emilioplatzer** [comment]
Hi. I'm sorry about not send replies in the weekend. 

I think that changing the order of parameters of query (sql, values, mask) is a good thing. Your module names pg-promise, and like fs-promise should have the same functionality of pg changing the callback with a returned promise. And like fs-promise will add new features. 

I think you are in the right way. 

A year ago I write a module https://github.com/emilioplatzer/motor-db that haves similar features. The main problem with it is that the test are not complete. Others problems:
 * The new features, the documentation and the test are in Spanish (I'm from Argentine)
 * Thera are a mix of features of diferent levels in the same level: 
    - pg functions returning promises (ES6-promises)
    - multi database (pg, sqlite and mysql)
    - special functions that control counts like yours none, one, many (in my module: ejecutar, dato or fila, todo)
    - logical nested transactions
    - named parameters (like "SELECT * FROM t1 WHERE year = :year", {year: 2014})
    - group parameters (like "insert into t1 (???FIELDS) values (???VALUES)", {year: 2014, alpha:1, betha:2} insted of write "insert into t1(year, alpha, betha) values ($1, $2, $3)", [2014, 1, 2])

What I learn in that moment?
 * I need solid tests. Otherwise, after a while, I begin to distrust my own code
 * I need to split the features in several levels and use more standars 
 * I need to colaborate with others

What can I suggest to you
 * If you need you can add a method ctx.oneValue("SELECT one_field FROM ... ") that returns a value insted of a row. 
 * Travis-CI have a way to test in postgres databases (I don't knew this a year ago). Brings to your code a empty database for each test build. 
 * If you want you can use Mocks to test without a real db. 
 * If you want to test with a real db and want to know if the calls to certain pg modue are like you expect you can use https://github.com/emilioplatzer/expect-called

 I think that I would to enhance pg-bluebird by adding some like one, many, all, value, etc. But I only begin if I write the test first. If I do it I notice you. 

Regards

**Comment by vitaly-t** [comment]
@emilioplatzer,

Thank you for your long feedback. I've been doing so many updates of lately, I think it is important to get as much feedback as possible first (from a few people that is).

By the way, regarding your suggestion:
>If you need you can add a method ```ctx.oneValue("SELECT one_field FROM ... ")``` that returns a value insted of a row.

You already can make such call, and the simplest form is:
```javascript
ctx.one("SELECT column from table");
```

I've just spent too much time writing all this, will try to stay away for couple days, see what kind of feedback I get :) So far the number of downloads on npmjs.org is promising :)

I was in a rush because I knew I was introducing too many breaking changes, so I wanted finalize them all and release before the end of the weekend, which I have done. You can see how much of the documentation has changed also ;)

**Comment by vitaly-t** [comment]
First test integration added ;) Will try writing the actual tests later.

**Comment by vitaly-t** [comment]
Tests have been added, and new release with tests is out. If you have something to add, please do in a separate subject, in case there are issues that is, as this one should be just left in the past now.

I'm locking it down ;)
