### ISSUE TITLE
Question: non-default promise library with Typescript

### ISSUE THREAD

**Issue by mibanez** [vitaly-t/pg-promise#202]
I was trying to use Bluebird with pg-promise and Typescript like this

```
import * as PGP from 'pg-promise';
import * as Promise from 'bluebird';

const pgp = PGP({ promiseLib: Promise });
const db = pgp('postgres://test:test@localhost:5432/testdb');

function getAllUsers(): Promise<any[]> {
    return db.any('SELECT * FROM users');
}
```

But then I got ```Type 'Promise<any>' is not assignable to type 'Bluebird<any>'```
I know I can use Bluebird resolve, but it would be nice if db.any could return a promise of the type configured with promiseLib.
Any ideas of can i do this?

**Comment by vitaly-t** [comment]
You should read [this]https://github.com/vitaly-t/pg-promise/blob/master/typescript/ext-promise.d.ts).

**Comment by uhef** [comment]
I've read the links provided and still having hard time figuring out how to configure pg-promise so that typescript handles promises returned from pg-promise functions as bluebird promises instead of native promises. Closest I've come to success is to manually configure `ext-promise.d.ts` as explained (here)[https://github.com/vitaly-t/pg-promise/blob/master/typescript/ext-promise.d.ts] within `node_modules`. But surely the answer is not to install pg-promise as dependency and then modify pg-promise code within `node_modules`. Somehow I suppose the configuration should be achievable within the application depending on pg-promise.

**Comment by vitaly-t** [comment]
@uhef The problem is, after many promises, the TypeScript still failed to deliver the support for generics as parameters. See this question: [Using a custom promise as a generic type
](https://stackoverflow.com/questions/36593087/using-a-custom-promise-as-a-generic-type).

**Comment by uhef** [comment]
I see.

One way to improve the current situation would be to remove typescript type definitions from pg-promise and host them as a separate project. Currently pg-promise comes with type definitions which results in a situation where user needs to make modifications to pg-promise project in `node_modules`. If pg-promise would ship without type definitions and type definitions would be hosted in a separate project user could install pg-promise in to `node_modules` and clone pg-promise type definitions to a separate folder within the using project (lets say `types`). `types` folder could be added to version control and user could make required modifications there to take bluebird into use. In order to read type definitions from `types` one would just need to modify the `tsconfig.json` file and add `types` folder under `typeRoots` - key like this:

```
"typeRoots": [ "node_modules/@types", "types" ]
```

**Comment by vitaly-t** [comment]
@uhef another approach would be, as suggested in file [ext-promise.d.ts](https://github.com/vitaly-t/pg-promise/blob/master/typescript/ext-promise.d.ts):

> if you do not want to get these settings overridden during an update or deployment,
 it may be a good idea to copy all of the *.ts files into your own project, and use them from there.

...which considering that the definition don't change often, is perhaps the best solution ;)
