### ISSUE TITLE
Cannot execute functions that return "record" type with arbitrary columns

### ISSUE THREAD

**Issue by devspacenine** [vitaly-t/pg-promise#21]
In order to execute a function that returns multiple rows, you need to be able to define column aliases when selecting from a function. Any plans to support this?

**Comment by vitaly-t** [comment]
Any test conducted with functions would return multiple records, based on a table, so columns are provided automatically.

Therefore, could you, please clarify your question, preferably with an example?

**Comment by devspacenine** [comment]
Sorry, should have clarified. I was in a rush when posting. When executing a function that returns multiple rows with arbitrary columns (not based on a table), you need to be able to define column aliases. For Example, using this test function:

``` sql
CREATE OR REPLACE FUNCTION test()
     RETURNS SETOF record AS
$func$
     VALUES (1, 2), (3, 4);  -- 2 rows with 2 integer columns
$func$ LANGUAGE sql;
```

Calling it like this with pg-promise:

``` javascript
dbServer.func('test', []) 
    .then(function(data) {
        console.log('Data: ', data);
    }, function (err) {
        console.log('Error: ', err);
    });
```

Will execute:

``` sql
SELECT * FROM test()
```

Postgres will respond with *ERROR:  a column definition list is required for functions returning "record"*

To successfully execute the function you would select with column aliases:

``` sql
SELECT * FROM test() AS f(a int, b int)
```

**Comment by vitaly-t** [comment]
This looks like a very special case. Why not just execute a generic query then?

```javascript
db.query("select * from test() as f(a int, b int)");
```

**Comment by vitaly-t** [comment]
After having played with the function you provided, I'd like to add the following...

You do not need to add any letters in front of the columns specification, i.e. the following syntax will suffice:
```javascript
db.query("select * from test() as (a int, b int)");
```

And when we call a function we do not have any information regarding the expected column names or their types, which means you would have to specify them all on the client side separately, and since it cannot be done automatically, there is no convenience in doing that at all, and thus no point.

I will stay with my original recommendation of using regular queries for such function calls, as posted earlier.
