### ISSUE TITLE
Managing read replicas

### ISSUE THREAD

**Issue by akshayp** [vitaly-t/pg-promise#222]
First off, this is an amazing library and has made our code base better so thank you for all the hard work you put into it! 

What is your recommended way of managing connections to postgres read replicas? I have a setup currently where there's one master and many replicas and would like to send some frequent queries to the replicas to ease some load off the master

**Comment by vitaly-t** [comment]
`postgres read replicas` I never came across those, no idea what that is.

**Comment by akshayp** [comment]
@vitaly-t It's essentially what AWS calls a database slave except it's primary function is meant for read only queries

**Comment by vitaly-t** [comment]
Do you want to set aside a single dedicated connection for some special read-only operations?

**Comment by akshayp** [comment]
Correct, non mission-critical read only operations would be routed to a database slave

**Comment by vitaly-t** [comment]
Normally, all connection are automatically acquired from the connection pool and then released back.

There can be however some very special cases when one might want to create a connection separately from the pool, like in case of a permanent event listener `LISTEN` / `NOTIFY`, as I show here: [LISTEN / NOTIFY](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#listen--notify).

From what you told me, it sounds like another special case when you want to declare a global connection to be used for some special cases.

This means you can create it by calling `db.connect({direct: true})`. This creates a new connection outside of the pool, see the [API for method connect](http://vitaly-t.github.io/pg-promise/Database.html#.connect).

But be careful, because:

1. It is not meant to be scalable, you cann just keep creating and releasing such direct connections;
2. Since it is out of the connection pool's control, such connection is vulnerable to unreliable database connections, meaning that if you lose your database connection, your object becomes dead, and you would need to pick it up yourself, whereas the connection pool would do it for you automatically.
