### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by waynehoover** [vitaly-t/pg-promise#25]
There are many different postgres promise libraries out there, is this one ready for production use? Also why would I want to use this library over something like http://knexjs.org/. These types of questions might want to be addressed in the readme or wiki.

**Comment by vitaly-t** [comment]
In essence, this library is more specific and much simpler, no learning curve, because it just joins [node-postgres](https://github.com/brianc/node-postgres) library with the [standard promises](https://promisesaplus.com/), without building much of a custom protocol on top of that.

And yes, it has been production ready for a while now. Also, consider this - the more protocol you try to build on top of the database logic, the more bugs you are likely to end up with.

**Comment by vitaly-t** [comment]
@waynehoover , I have added an [introductory note in WiKi](https://github.com/vitaly-t/pg-promise/wiki/Why-use-it%3F).

If this answers your questions, please close the issue, and if not - let me know ;)

**Comment by waynehoover** [comment]
Yes, thanks.
