### ISSUE TITLE
Cannot use named paramters after a bracket

### ISSUE THREAD

**Issue by BartTK** [vitaly-t/pg-promise#257]
Using a named parameter after a bracket results in a parse error. 
`SELECT * FROM some_table WHERE id IN some_stored_procedure($<some_parameter>)`
Results in `syntax error at or near "$"`.
I tried different open-close pairs, but none of them work. Using `$1` seems to work though that is not practical in my specific situation.

**Comment by vitaly-t** [comment]
This means you are using either [ParameterizedQuery] or [PreparedStatement], documentation for which clearly states that you only have access to the basic `$1, $2` formatting, because those are formatted by the server.

[ParameterizedQuery]:http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html
[PreparedStatement]:http://vitaly-t.github.io/pg-promise/PreparedStatement.html
