### ISSUE TITLE
data with $s in quoted strings

### ISSUE THREAD

**Issue by ZeusIV** [vitaly-t/pg-promise#27]
Was getting a lot of problems with my passwords becoming invalid. I  finally tracked it down to parameterised queries. I am using squel...toParam() which returns something like this
text "UPDATE users SET password = $1 WHERE (id = $2) AND (resetpass = $3) RETURNING *"
values[0] "$2a$08$4ImbUVRRASc1xlNFQ"
values[1] 3
values[2] "4ybcAQN8"
then calling pg-promise like so
return db.query(text, values);
which mangles the password to
3a$08$4ImbUVRRASc1xlNFQ
the initial $2 in the password has been replaced by the '3' in values[1]

You shouldn't be replacing $n in quoted strings. 
Imagine an 
UPDATE bids SET text = $1 WHERE id = $2
values[0] "I agree to pay you the unreservedly binding sum of $2.00 for this used bus ticket"
values[1] 34856

Thanks Zeus

**Comment by vitaly-t** [comment]
What really happens here:

Step1: $1 is replaced with the specified string;
Step2: $2 is replaced with the specified parameter.

And since the result Step1 is another $2 introduced, it is replaced again in Step 3.

This is a very special case, one I couldn't think of yet, but technically is a bug indeed.

Thank you for finding this.

**Comment by vitaly-t** [comment]
@ZeusIV The current code in the master branch already has this issue fixed. I will need to finalize some changes and then release it as 1.5.0 ;)

**Comment by vitaly-t** [comment]
This bug has been fixed in [Release 1.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.1.5.0)
