### ISSUE TITLE
Sequential execution of queries in a transaction

### ISSUE THREAD

**Issue by nilspreusker** [vitaly-t/pg-promise#307]
Hi Vitaly,

I'd like to **execute several queries in sequence, wrapped into a transaction**. Now, I've got an implementation using `batch`. 

However, while it works, I'm suspecting that it works only by chance :)

Following your README I came up with the following:

```
db.tx(t => {
        let deleteQuery = t.none(`DELETE FROM TEST_TABLE WHERE MY_ID = ${myId}`)
        let cleanUpQuery = t.none(`UPDATE TEST_TABLE SET RANK = RANK-1 WHERE MY_ID = ${myId} AND RANK > ${index}`)
        t.batch([deleteQuery, cleanUpQuery])
          .then(() => {
            // ...
          }).catch(error => {
            // ...
          })
```

Then, reading on in your README, I noticed that `batch` resolves all queries **asynchronously**. 

Digging deeper, the spex documentation of `batch` metnions

> Array of mixed values (it can be empty), to be resolved asynchronously, in no particular order.

So I'm wondering:

* to execute queries in deterministic order, does the above code work reliably?
* I presume I'd have to use `sequence`. In that case, how do I pass data into the `source` function in order to construct the queries? Can you help me out with an example?

Thanks!
Nils

**Comment by vitaly-t** [comment]
The library with its promises executes the requests asynchronously, because IO works asynchronously in Node.js

However, since the queries within transaction execute against the same IO channel, they become synchronized with respect to each other, i.e. the sequence of queries executed will be exactly as you defined it.

And one usually places `then/catch` outside of the trsnaction.

```js
db.tx(t => {
        let deleteQuery = t.none(`DELETE FROM TEST_TABLE WHERE MY_ID = ${myId}`)
        let cleanUpQuery = t.none(`UPDATE TEST_TABLE SET RANK = RANK-1 WHERE MY_ID = ${myId} AND RANK > ${index}`)
        return t.batch([deleteQuery, cleanUpQuery])
})
    .then(() => {
        // ...
     })
     .catch(error => {
            // ...
     });
```

**Comment by nilspreusker** [comment]
Excellent, thanks for the quick answer and keep up the great work!

**Comment by ferlopez94** [comment]
Hi!
I'm learning how to use pg-promise and I have the situation when I need to insert like 50 records to populate my test database. Researching I came with batch and pgp.helpers but the problem is that I also need to insert some info that depends on the generated id of another insert. The solution is:

```
let populateDatabase = () => {
   let cs = new pgp.helpers.ColumnSet(['col_a', 'col_b'], {table: 'table1'});
   let valuesInsert = pgp.helpers.insert(values, cs);

   db.tx(t => {
      return t.one('INSERT INTO user (first_name, last_name) VALUES (${first_name}, ${last_name}) RETURNING id', user)
         .then(data => {            
            user.id = Number(data.id);
            personalMeasurements[0].id_user = user.id;
            personalMeasurements[1].id_user = user.id;

            const q1 = t.none('INSERT INTO device (model) VALUES (${model})', device);
            const q2 = t.none(valuesInsert);
            const q3 = t.one('INSERT INTO personal_measurement (personal_measurement_date, height, id_user) VALUES (${personal_measurement_date}, ${height}, ${id_user}) RETURNING id', personalMeasurements[0]);
            const q4 = t.one('INSERT INTO personal_measurement (personal_measurement_date, height, id_user) VALUES (${personal_measurement_date}, ${height}, ${id_user}) RETURNING id', personalMeasurements[1]);
            
            return t.batch([q1, q2, q3, q4]);   
         });
   }).then(data => {
      console.log('populateDatabase success', data);      
   }).catch(error => {
      console.log('populateDatabase error', error);
   });
};

populateDatabase();
```
I wanted to ask you:
1. Is it ok to make a simple insert and inside the then clause have the batch which includes a pgp.helpers.insert? I just want to make sure I'm not implementing it with a bad pattern. I saw some examples but there are with different situations.
2. Do you recommend to use pgp.helpers.insert even when I have to insert 2 records? So instead of q3 and q4 have pgp.helpers.insert(valuesPersonalMeasurements, csPersonalMeasurements).

Thanks!

**Comment by vitaly-t** [comment]
@ferlopez94 the easiest way is to patch your `values` (array of objects) with the generated `user_id`, right after you get it. Then you can do `helpers.insert` to generate the complete insert query.

Not only it is ok, but you should do it inside the transaction, i.e. only the creation of the `ColumnSet` should be external. The reason is to let the transaction callback handle exceptions, in case `helpers.insert` generates one, thus adhereing to the transaction logic.

> Do you recommend to use pgp.helpers.insert even when I have to insert 2 records?

It still will be twice as fast, that's for sure ;)

**Comment by ferlopez94** [comment]
Thank you so much for the feedback! I took them into consideration and after reading more about ColumnSet and ColumnConfig, I changed the code to the following:

```
let populateDatabase2 = () => {
   let csValues = new pgp.helpers.ColumnSet(['col_a', 'col_b'], {table: 'table1'});

   let csDevice = new pgp.helpers.ColumnSet([{name: 'model'}],
                                           {table: 'device'});

   let csUser = new pgp.helpers.ColumnSet([{name: 'first_name', prop: 'firstName'}, 
                                           {name: 'last_name', prop: 'lastName'}],
                                           {table: 'user'});

   let csPersonalMeasurement = new pgp.helpers.ColumnSet([{name: 'personal_measurement_date', prop: 'personalMeasurementDate'},
                                                          {name: 'height'}, 
                                                          {name: 'id_patient', def: () => user.id}],
                                                          {table: 'personal_measurement'});                                          
   
   db.tx(t => {
      let userInsert = pgp.helpers.insert(user, csUser) + 'RETURNING id';

      return t.one(userInsert)
         .then(data => {            
            user.id = Number(data.id);
            
            let deviceInsert = pgp.helpers.insert(device, csDevice);
            let valuesInsert = pgp.helpers.insert(values, csValues);
            let personalMeasurementInsert = pgp.helpers.insert(personalMeasurements, csPersonalMeasurement) + 'RETURNING id';

            const q1 = t.none(deviceInsert);
            const q2 = t.none(valuesInsert);
            const q3 = t.many(personalMeasurementInsert);
            
            return t.batch([q1, q2, q3]);   
         });
   }).then(data => {
      console.log('populateDatabase success', data); 
      personalMeasurements.forEach((personalMeasurement, index) => personalMeasurement.id = data[2][index].id);     
   }).catch(error => {
      console.log('populateDatabase error', error);
   });
};

populateDatabase();
```
The code works perfectly and  I can see clearly the benefits of pgp.herlpers :D 

PD: In the `then` clause, I implement a `forEach` in order to add the generated id for personalMeasurements, maybe this can be a problem where multiple generated id return, but because I'm not inserting more than 5 I don't think it's a problem.

You mentioned [here](http://stackoverflow.com/questions/39119922/postgresql-multi-row-updates-in-node-js) that doing this way is "completely safe, as all data types are going through the library's query formatting engine to make sure everything is formatted and escaped correctly.", so does it prevent us from SQL injection?

**Comment by darrinholst** [comment]
> However, since the queries within one transaction execute against the same IO channel, they become synchronized (by the server) with respect to each other, i.e. the sequence of queries executed will be exactly as you defined it.

This no longer appears to be the case. I had a list of 1 delete and 7 inserts and the delete would consistently be run after 1 or 2 inserts. Switching to sequence fixed it for me...

``` js
  return db.tx(tx => tx.batch(commands));
```

``` js
  return db.tx(tx => tx.sequence(i => commands[i]));
```

Not sure what changed since the `batch` used to work. Running against heroku postgres 9.6.8 if it matters.

**Comment by vitaly-t** [comment]
@darrinholst This is odd, because inside a transaction you have just one IO channel, so the first query of `DELETE` cannot be outrun by queries that follow, as it will definitely arrive into the server first.

Anyways, with the new ES6 Generators or ES7 `async/await` you no longer need to care about it, as all operations are strictly sequenced, unlike the traditional promises.

**Comment by darrinholst** [comment]
@vitaly-t yep, my bad. I was creating the queries off of `db` and not the `tx`. False alarm.

**Comment by vitaly-t** [comment]
@darrinholst That is the most typical mistake, happens to people all the time. Here's the most recent one: [Why does insert query results remain in database after transaction rollback?](https://stackoverflow.com/questions/50011127/why-does-insert-query-results-remain-in-database-after-transaction-rollback-pg).

😄
