### ISSUE TITLE
Helpers.insert not working

### ISSUE THREAD

**Issue by ntaboada** [vitaly-t/pg-promise#365]
Hi there,

I am trying to implement an insert query using the helper for multiple rows but i can't.
**I am exporting db like this:**

```js
_const pgp = require('pg-promise')(options);
const db = pgp(cn);

export default db;_
```

**An importing in my DAO like this:**

```js
import sql from './sql/index';
import db from '../../config/database';

_export default class UsersDao {

    static all() {
        return db.any(sql.select);
    }

    static save(user) {
        return db.none(sql.create, [user.groupid, user.steamid, user.steamid64]);
    }

    static saveUsers(users){
        return db.$config.pgp.helpers.insert(users, ['STEAM_GROUP_ID_64', 'STEAM_ID_64'], 'CSGO_USERS');
    }
}
```

The all and save queries are running fine, but saveUsers is not working. I tried as i readed on documentation (db.helpers.insert...) but got "undefined" on the helper. Doing this way, it seem that query its running well, but i do not see rows been inserted.

The users param :
```
[{ STEAM_GROUP_ID_64: '10', STEAM_ID_64: '7 },{ STEAM_GROUP_ID_64: '2',   STEAM_ID_64: '3' }]
```
Please help me!

**Comment by vitaly-t** [comment]
Methods in namespace [helpers] all generate queries, that's their whole purpose, they do not execute them, the main library does that.

When you call [helpers.insert], it generates and returns the complete `INSERT` query, and you do not execute it anywhere.

In addition to it, you should do the following:

* create the `ColumnSet` statically, outside, so it can be reused
* generate everything everything either inside a task or try/catch, so that way any query-generating error can be reported the same as the query itself.

All being said, yous code would be something like:

```js
const helpers = db.$config.pgp.helpers;

const cs = new helpers.ColumnSet(['STEAM_GROUP_ID_64', 'STEAM_ID_64'], {table: 'CSGO_USERS'});

static saveUsers(users) {
    return db.task(t => {
        const query = helpers.insert(users, cs);
        return db.none(query);
    });
}
```
