### ISSUE TITLE
Generated column not recognized

### ISSUE THREAD

**Issue by Tobbeman** [vitaly-t/pg-promise#394]
Hello!
I followed the instructions on "https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise" however the query can't be run. When I try to use it I get an error saying that "has_product" does not have column "product_bundleId".

The query generated by the helper:
insert into "has_product"("product_bundleId","productId") values('1','1'),('1','1')

I tried to write it myself and removed all citation signs, which resulted in it running fine. 
Any ideas?

**Comment by vitaly-t** [comment]
This usually happens when you misuse the name case, i.e. your `product_bundleId` in the database probably has a capital in it.

**Comment by Tobbeman** [comment]
I thought that captilizing could be the issue, have tried with both small and big I in Id to little avail.
The sql is atleast defined as: "product_bundleId INT REFERENCES product_bundles(id) ON DELETE CASCADE".

And like I said, using the same query without quotation marks worked fine, does that not imply that the quotation marks can be the source of the issue?

**Comment by vitaly-t** [comment]
Your definition is invalid: `product_bundleId INT REFERENCES product_bundles(id) ON DELETE CASCADE`, because it uses capital `I` in it, without quotes. Read about use of capitals in PostgreSQL and how the server handles them.

You should either use it without capital, or put into quotes for the server to be able to tell the difference.

**Comment by vitaly-t** [comment]
To explain it better, when you create `product_bundleId` without quotes, it automatically creates it with all small letters. You would have to place it into quotes in order to create it in the right case.

You need to read about how PostgreSQL treats camel cases.

That's why if you replace in your code with `"product_bundleid"`, i.e. without capital, it will work, because that's what you actually have.

**Comment by vitaly-t** [comment]
@Tobbeman any feedback?

**Comment by Tobbeman** [comment]
Ahh, I thought closed issues should not be responded to!
Yes you were right, I did try to use small letters when creating the columns but still had big in the values. Using small on all places fixed my issues! Thank you for time
