### ISSUE TITLE
Getting "Error: Loose request outside an expired connection." with async/await

### ISSUE THREAD

**Issue by suricactus** [vitaly-t/pg-promise#404]
I found kind of unexpected behavior of the library at first glance. When running the code below in a transaction, I keep getting the "Error: Loose request outside an expired connection." error. If I modify the example just a little, either by having only one query in  `innerFunc` or by adding `await` with query after last query in `cb`, everything works fine.

After carefully investigating it, I think I found out the reason why it happens, but it's not documented anywhere or at least I didn't find this special case. Adding `await` makes this code example a working one because all queries in the transaction are queued and executed in order and the `await` keyword ensures there is no race condition and transaction being closed before everything is executed.

I found this by using a cursor and opening a transaction inside every record the cursor finds. The example below is oversimplified and the error is obvious, but in real world it may stay hidden for days, like in my case. 
```
const config = { ... }; // change for your db
const pgp = require('pg-promise')(config.pgConfig);
const db = pgp(config.conString);

db.tx(cb);

async function cb(tx) {
  let count = { a: 0 };

  innerFunc(tx, count);
  innerFunc(tx, count);
  
  count = await innerFunc(tx, count); // comment this and everything is broken

  console.log('It works!', count)
}

async function innerFunc(tx, count) {
  const first = await doSth(tx, count); // keep only one db request in this function and everything is fine, despite commenting the "await" part 5 lines above
  const second = await doSth(tx, count);

  return second;
}

function doSth(tx, count) {
  return tx.one('select $1::int + 1 AS a', count.a);
}
```

I think someone having the same problem may find this useful.

**Comment by vitaly-t** [comment]
>  it's not documented anywhere

It is documented plenty. There are tons of duplicate issues others opened in the past, and there are issues on StackOverflow, like this one: [Loose request outside of an expired connection](https://stackoverflow.com/questions/44462833/loose-request-outside-of-an-expired-connection).

Please see [Contribution Notes](https://github.com/vitaly-t/pg-promise/blob/master/CONTRIBUTING.md).

---

Your code is simply invalid. The error you are getting is because you create queries inside the transaction, and you fail to chain them to the transaction logic:

```js
innerFunc(tx, count);
innerFunc(tx, count);
```
This creates loose promises. The correct call to chain the result must be:
```js
await innerFunc(tx, count);
await innerFunc(tx, count);
```

Another issue:
```js
db.tx(cb);
```
where you again create a loose promise. You must always provide at least a catch handler:
```js
db.tx(cb)
    .catch(error=>{
    });
```

**Comment by vitaly-t** [comment]
P.S. Note that the error itself `Loose request outside an expired connection` was refactored in version [6.5.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.4).
