### ISSUE TITLE
Wildcard in query

### ISSUE THREAD

**Issue by gilly3** [vitaly-t/pg-promise#42]
How can I perform a wildcard search?

```js
db.manyOrNone("select * from items where name like $1", "%Joe's%")
```

I know I can use `'%$1^%'`, to avoid escaping the wildcard character, but that also leaves the quotes unescaped.  I want to sanitize my input *and* use wildcards.

**Comment by vitaly-t** [comment]
The way that raw-text formatting works, as opposed to default variable formatting, it leaves the safety of it in your hands. It only cares that the value is not `undefined` and not `null`, because those may have any kind of interpretation.

If you anticipate symbol `'` as part of your filter, you would need to take care of it on your side. This is a fairly unique case after all.

And you have some options here.

First of all, you can simply pass your filter value into a function that will fix `'` for you. Here's example of such function, as it is used inside the library itself when fixing quotes:

```javascript
////////////////////////////////////////////
// Replaces each single-quote symbol '
// with two, for PostgreSQL compliance.
function fixQuotes(text) {
    return text.replace(/'/g, "''");
}
```
once parsed through such function, you would use the `^` with your variable to indicate that you want raw-text insertion.

Another option, a more elegant one, - you can create your own type that represents a filter...

**Comment by vitaly-t** [comment]
Please follow up, and close the issue, if your question is answered.

**Comment by vitaly-t** [comment]
Closing the question due to inactivity.

**Comment by gilly3** [comment]
Thanks for your detailed response.  Very helpful.  `pgp.as.format()` is particularly useful.

**Comment by vitaly-t** [comment]
The approach suggested here is no longer necessary, since version [3.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.4.0), which added support for [Open Values](https://github.com/vitaly-t/pg-promise#open-values), using which we can write complex filters right in-line, without an additional type.

```js
db.manyOrNone("select * from items where name like '%$1#%'", "Joe's")
```
- variable `$1#` will properly escape the text, but won't add surrounding quotes.

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
