### ISSUE TITLE
Dynamic where clause builder

### ISSUE THREAD

**Issue by jaimesangcap** [vitaly-t/pg-promise#544]
Is there a way to build a where clause dynamically? I've already seen the docs, what I can only find is for inserts and updates using `ColumnSet`.

If you don't have plans for it. May I know the reasoning behind and how will you recommend doing it in pg-promise?

**Comment by vitaly-t** [comment]
Inserts and updates are special cases that require providing repeated series of data that needs to be escaped automatically. That's why this library supports it. Any other part of a query you can generate yourself. And this library is NOT an ORM, it is not supposed to generate all your queries dynamically, its purpose is to execute pre-generated queries.

**Comment by jaimesangcap** [comment]
Thank you for answering. I understand why your point. I guess I have to roll my own where builder.
