### ISSUE TITLE
Multi-line ts import crashes compile 

### ISSUE THREAD

**Issue by xShirase** [vitaly-t/pg-promise#557]
### Expected behavior
normal ts/js compilation

### Actual behavior
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof pgPromise' has no compatible call signatures.

### Steps to reproduce
run the examples in README, the multiline import with wildcard doesnt compile for me ie:
```typescript
import pgPromise, {IMain, IDatabase, IOptions } from 'pg-promise'; ---> works
```

```typescript 
import {IMain, IDatabase, IOptions} from 'pg-promise';
import * as pgPromise from 'pg-promise';   ---> error TS2349
```
### Environment

* Version of pg-promise: "pg-promise": "^8.4.6"
* OS type (Linux/Windows/Mac): win & ubuntu
* Version of Node.js: 8.10

**Comment by xShirase** [comment]
ts-node v7.0.1
node v8.12.0
typescript v3.1.1

**Comment by dimfeld** [comment]
Do you have esModuleInterop or allowSyntheticDefaultImports set in your typescript compiler options?  These options change typescript's import behavior in a way that could cause the behavior you're seeing.

**Comment by vitaly-t** [comment]
Modern TypeScript has so many special options these days, that some of them indeed may result in `pg-promise` script not transpiling correctly. This however does not merit documenting all such cases.

The important thing is, examples like [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) builds correctly, without issues, while relying on the default TypeScript settings, i.e. it builds fully without any `tsconfig.json`.

So, if something does not build using the default TypeScript profile, it is worth documenting. Otherwise, it is not.
