### ISSUE TITLE
I'd like to use the new query syntax on prepared statements

### ISSUE THREAD

**Issue by nickretallack** [vitaly-t/pg-promise#56]
I tried it, but it didn't work:

```javascript
db.one({
  name: 'test-query',
  text: 'select id from file where id = ${id}',
  values: {
    id: 1,
  }
}).then(function(row){console.log(row)}).catch(function(err){console.log(err)})
```
```
error: syntax error at or near "$"
```

I see the documentation specifically says ["Using the syntax supported by node-postgres"](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#prepared-statements).  I guess that's my only choice?  I guess this is a bit harder to implement, but it's just an argument mapping, so it should be possible...

**Comment by vitaly-t** [comment]
You are mixing two things that are handled by two separate libraries.

Prepared Statements are passed into `node-postgres` directly, which is the library that executes them.

And at the same time you are trying to use the syntax that's used within `pg-promise` for query formatting. 

Those are two separate things. Prepared Statements must adhere to [their syntax in node-postgres](http://www.postgresql.org/docs/9.4/static/sql-prepare.html).

**Comment by nickretallack** [comment]
I realize that's how it's set up now.  However, I'm not sure what's stopping you from translating the arguments from one style into the other.

**Comment by vitaly-t** [comment]
That's not possible, because there is no conversion from Named Parameters to index-based parameters. It is an entirely different mapping logic.

**Comment by nickretallack** [comment]
Sure there is.  Find the substitution parameters, sort them by name, and replace them with numbers.

**Comment by vitaly-t** [comment]
Just to clarify a little...

First of all, Named Parameter syntax is supported by pg-promise, and it implies a certain type of formatting, while node-postgres formats values a bit differently. This goes for Date, Number, Array, at the very least.

Second, Named Parameter syntax supports ^ for raw-text insertion, which node-postgres does not.

I understand that Prepared Statement formatting is awkward, but at least it is strictly defined, whereas if we try to mess with it, there is no clear path as to how it should work, will only cause more questions.

I personally do not like Prepared Statements at all, and I think they are mostly a waste of time, because:

Their performance gain is only possible for very complex queries, while only slowing the simple once. And even for the complex ones the gain is often negligible;
SQL Injections can by avoided differently, through the website security design. And it is also one of the least exploitable things, because it is very hard to make useful.

**Comment by SmaugTheGreat** [comment]
> Their performance gain is only possible for very complex queries, while only slowing the simple ones. And even for the complex ones the gain is often negligible;

could you please elaborate on that topic? I couldn't find any sources so far that prepared statements slow down anything? Maybe a link or something?

Thanks!

**Comment by vitaly-t** [comment]
I've done testing in this area some tome ago, using massive insert queries. I saw something like 5% drop in performance with Prepared Statements.

A simple INSERT is a simple operation, and its execution cache has no value on the server, it only gets in the way.

Execution path is only of value when there is an extra logic within the query.

I'm not sure if there is any article about it out there, it's just the result of some vigorous tests.
