### ISSUE TITLE
Statement timeout in transaction returns a broken connection to the pool

### ISSUE THREAD

**Issue by joux3** [vitaly-t/pg-promise#566]
### Expected behavior

After a statement timeout in transaction, the used connection will be working properly when used again from the pool.

### Actual behavior

pg-promise does not rollback the transaction when a statement timeout has happened in it. This connection will be in a transaction aborted state and next user of it from the pool can not run any queries.

### Steps to reproduce

1. run a transaction
2. cause a statement timeout in that transaction
3. try to reuse to connection and see that it fails

Here is a repro case: https://gist.github.com/joux3/a29727968f7195eb640959013fab319f

### Environment

* Version of pg-promise: 8.5.2
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.12.0

### Extra info

The `code` field for the statement timeout error is `57014`. This causes the rollback not the be issued: https://github.com/vitaly-t/pg-promise/blob/ee34110368f29b14f913665e8803c86361ec3f00/lib/utils/index.js#L229-L238

**Comment by vitaly-t** [comment]
That code was an attempt to mediate a [long-standing issue in the driver](https://github.com/brianc/node-postgres/issues/1454). It is, of course, cannot be perfect, I only provided for the most common cases of losing a connection during a long transaction. If you have a different case, and can offer an improvement over this already an ugly work-around, a PR is welcome.

Ideally, we all want to see the issue fixed in the driver, but I'm tired chasing it, without result.

**Comment by vitaly-t** [comment]
P.S. There is a chance that [this PR](https://github.com/brianc/node-postgres/pull/1503) resolved it, but it needs a thorough testing.

**Comment by vitaly-t** [comment]
@joux3 as per my comments earlier, there is a chance that the whole issue was resolved in the latest driver.

So please try this first:

```js
function isConnectivityError(err) {
    return false;
}
```

and see if your error still happens or not.

**Comment by joux3** [comment]
Always returning `false` from `isConnectivityError` does fix my issue (the PR just causes `false` to be returned for this exact case). I agree, this looks like the optimal path.

Luckily this issue does not cause me to hurry: I could work around this specific issue in my specific case by using a task instead of a transaction, which of course is not always possible.

Is there something I could do the help test the driver changes? At least modifying the repro case to an actual `pg-promise` test case should not be too much work.

**Comment by vitaly-t** [comment]
@joux3  After applying all the latest updates, some tests and considerations, I ended up implementing the very same change as was originally in your PR.

The reason is, even though the library now can work without function `isConnectivityError` at all, it works better/smarter with that verification. So I left it, amending with query cancellation exception.

It was all released in [version 8.5.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.5.3).
