### ISSUE TITLE
Connection not closing (since today)

### ISSUE THREAD

**Issue by Portur** [vitaly-t/pg-promise#603]
Hi I'm not sure if this is relevant to #600 or maybe a side effect of it but we hit max connections from a cloud hosted express app.

The app has been limited to mostly 2 instances during load and only uses simple `SELECT` and `INSERT` calls.

The implementation is as follows:
```javascript
 const pg = require('pg-promise')({});
 const database_client = pg({
      "database": "db",
      "host": "00.00.00.00",
      "user": "user",
      "password": "password",
      "port": 5432
    });

//and then through out the app
database_client.none({ text: query_text, values: query_values })
database_client.any(query)

```

### Expected behavior
Connections open and close using the built-in connection pooling from `node-postgres`.

### Actual behavior
Connections are suddenly not getting closed.

### Steps to reproduce
Unsure. Connections have been successfully managed for the lifetime of the app.

### Environment
Google Cloud Platform - App engine Flexible.

* Version of pg-promise: 8.5.4
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 10

![image](https://user-images.githubusercontent.com/24350810/55953014-50ddc000-5c5b-11e9-875b-5ebd96244670.png)

Edit : added `const pg...`

**Comment by Portur** [comment]
Sorry, This was a rouge service. All is well

**Comment by OrKoN** [comment]
I believe I see a similar issue with `8.6.4` but I cannot prove that it's related to pg-promise/pg-pool yet. After some unknown event, the number of open connections grows to a maximum and open connections are not re-used and new ones cannot be created, so that every request is timing out presumably waiting for a db connection (endpoints which don't use database work fine, cpu/mem usage is also normal). 

![Screen Shot 2019-05-06 at 1 52 58 PM](https://user-images.githubusercontent.com/399150/57224147-bf1e6400-7008-11e9-8e16-b8d632372361.png)

In `pg_stat_activity` all those connections are marked as idle and no requests comes though. The db is also healthy and all queries work via psql.
