### ISSUE TITLE
Warnings with Bluebird 3.0

### ISSUE THREAD

**Issue by oliversalzburg** [vitaly-t/pg-promise#62]
When I enable warnings in `Promise.config`, I get a lot of warnings related to pg-promise.

```
Warning: a promise was created in a  handler but was not returned from it
    at $p (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\node_modules\pg-promise\lib\index.js:1005:12)
    at $connect (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\node_modules\pg-promise\lib\index.js:733:12)
    at taskProcessor (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\node_modules\pg-promise\lib\index.js:478:16)
    at Database.obj.task (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\node_modules\pg-promise\lib\index.js:410:16)
    at MessageManager.AbstractDataManager$list [as list] (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\src\data\manager.js:428:17)
    at Function.list (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\src\controller\message.js:109:23)
    at Job.wrapper [as job] (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\node_modules\lodash\index.js:3592:19)
    at Queue$next [as next] (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\src\job\queue.js:62:14)
    at startNextJob (c:\Users\OliverSalzburg.HARTWIG\FairManager Projects\core\src\job\queue.js:76:15)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

It doesn't really make sense to me, because, as far as I can tell, the promise *is* returned.

**Comment by vitaly-t** [comment]
There was a lot of debate over the new warning system added to Bluebird 3.0, which I personally hate, because every time I looked at it, it doesn't make sense. I think it was just a bad idea.

See my arguments against it: https://github.com/petkaantonov/bluebird/issues/832

The best I could convince Petka was to restore the functionality of `BLUEBIRD_DEBUG=0` that disabled those new warnings for the `development` mode. So if you set it, you won't see those warnings for Bluebird 3.0. That flag disabled the debug for `development` entirely.

I was told it is an opinionated implementation of promises after all, so I guess it is ok to come up with your own standard from time to time. Totally not, if you ask me, but that's just my opinion.

**Comment by vitaly-t** [comment]
In fact, I was so upset about it that kind of change, I started writing my own promise library, I called it [nitrous](https://github.com/vitaly-t/nitrous). It is at its very early stage of development.

I called this way because I want to focus of performance, first of all, to outperform Bluebird, that's my target, and plus simplicity. It may be a while before I get there, but I have started :)

**Comment by Cleod9** [comment]
@vitaly-t I just ran into this thread when trying to figure out why the latest bluebird was so noisy about warnings by default. I just wanted to let you know that I'm completely on your side, so you're not alone! Some of ben's comments in the other issue thread definitely came off as a bit sarcastic and rude :/

Anyway, there are two things that really bother me about that warning message:

1) A developer writing proper promise rejection handling will have more than enough insight to debug. I don't see any anti-patterns with not returning a promise, so it doesn't make sense to me to warn the user about anything like that (and if they did mean to return it but forgot, they'd get an obvious synchronous error when trying to call `then()` anyway)

2) I feel that a function from a library shouldn't be poking around to figure out if its instance was returned or not, leave that up to the compiler/linter to catch. Is it examining the stack or something to even determine this warning in the first place? Just seems strange to me, and this is my first time ever seeing something this progressive in terms of default warnings in a client-side JS library

I hope at some point that warning in particular is reconsidered, but for now I suppose I'll just adjust my config or downgrade

**Comment by vitaly-t** [comment]
Thanks, @Cleod9 

The most troubling example I found is when we have `return value;`, but the `value` can be `undefined`, so we get the same warning again that no value was returned.

And having `promise.reject()` should be treated the same as `throw;`, without any warning, it's just plain wrong.

Anyhow, with 3.0 it feels Bluebird went a little sideways, trying to introduce invalid non-existing standards for code diagnostics. I think they will find many developers rejecting the concept.

**Comment by vitaly-t** [comment]
Since this clearly turns into a rant about Bluebird, it won't have any resolution here, so I'm closing the issue.
