### ISSUE TITLE
Accessing multiple databases in one connection pool

### ISSUE THREAD

**Issue by Gustav0ar** [vitaly-t/pg-promise#662]
I have an app that has one database per customer on the same pg server (with lots of customers). I'm hitting connection limit opening pools for each database. So, I want to be able to access multiple databases in the same connection pool to avoid hitting those limits, executing separate queries/commands in each database. What is correct approach to do it? I couldn't find any straight answer for this kind of problem anywhere.

Thanks in advance!

**Comment by vitaly-t** [comment]
That's impossible, because each pool is database-bound, from the connection parameters it uses.

You need to create a separate [Database] object, with each own pool, and then limit the number of connections each pool is allowed to open.

```js
const cn = {
  host: 'localhost',
  port: 5432,
  user: 'user-name',
  database: 'db-name',
  max: 5 // set maximum number of connections in the pool to 5
};
```

You can set it all the way down to 1, if needs to be.

[Database]:https://vitaly-t.github.io/pg-promise/Database.html
