### ISSUE TITLE
Extra `'` on each end of result from `pgp.as.json()`

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#678]
### Expected behavior
A string like `JSON.stringify()`

### Actual behavior
An extra `'` is put on each end of the string

### Steps to reproduce
`pgp.as.json({"test": "this"})`

### Environment
* Version of pg-promise: 10.3.1
* OS type (Linux/Windows/Mac): macOS 10.14.6
* Version of Node.js: 12.13.1

**Comment by vitaly-t** [comment]
First, your expectation is wrong, because the standard `JSON.stringify` does not produce a string compatible with PostgreSQL.

And why don't you want single quotes on ends? That's how JSON is normally used within SQL. You can omit escaping altogether, by passing the `raw` flag to the method, but I do not know of your usage scenario to advise this.

**Comment by daveisfera** [comment]
Oh ok. I'm using it to convert the result retrieved from `pg-promise` to JSON to support output of `BigInt`, so it sounds like I do want `raw=true`.
Thanks!

**Comment by vitaly-t** [comment]
> I'm using it to convert the result retrieved from `pg-promise` to JSON to support output of `BigInt`

But that's a reversed operation. The library already gives you JSON. I'm confused what you need that function for. Can you provide an example?

**Comment by daveisfera** [comment]
We currently use `pg-query-stream` to get the result the result as [JSONL](http://jsonlines.org/) with each row of the result being a row in the response, so we need to be able write the `BigInt` values to the JSON response as a number and we were using `pgp.as.json()` to do that

**Comment by vitaly-t** [comment]
Ok, got it! :smile:
