### ISSUE TITLE
Integration or compatibility with the Express-Session module

### ISSUE THREAD

**Issue by JaxCavalera** [vitaly-t/pg-promise#69]
Is there an example of how to use pg-promise with Express-Session so postgresql can be used as the store?  I saw a module called "connect-pg-simple" but am concerned that using it with pg-promise might have conflicts as both use different versions of the pg library from what I can follow.

Any information would be really helpful as I tried googling this but turned up a bunch of results about tv show ratings and holding sessions to talk about parental guidance.  And this but I don't think it's related to this topic specifically: https://github.com/vitaly-t/pg-promise/blob/6012bf3b5cd3cce9934e538b6f67fade9d9e4542/README.md#configurable-transactions

**Comment by vitaly-t** [comment]
I don't see why you think `pg-promise` and `connect-pg-simple` would use a different `pg` version:

from `pg-promise`: `"pg": "4.x"`
from `connect-pg-simple`: `"pg": ">=2.7.0-0 <5.0.0-0"`

both will pull the same current version of pg - `4.4.3`. Plus there is such thing in npm as the package version override, so you can easily force the 2 packages use the exact same version.

And I would not expect any conflict, they should be able to work independently.

And no, Configurable Transactions got absolutely nothing to do with it.

Other than that, if somebody decides to implement a `pg-promise` version of `express-session` - that would be a welcome addition!

**Comment by vitaly-t** [comment]
I have looked at couple framework-specific implementations: [connect-session-sequelize](https://github.com/mweibel/connect-session-sequelize) and [connect-session-knex](https://github.com/llambda/connect-session-knex), and frankly, I don't any point in writing those in the first place.

The only thing that makes sense - they all were started at around the same time, spring 2014, so there was no usable implementation for PostgreSQL at all. But now that there 3 usable implementations already to work with PostgreSQL, I see no pint adding one more, because they all do the same thing, just implement it differently.

**Comment by voxpelli** [comment]
The `connect-pg-simple` module should absolutely work with this module. If it for some strange reason doesn't, then I would be happy to take bug reports for it.

`connect-pg-simple` is meant to be the smallest and simplest session library for Postgres so that it can be compatible with and usable for as many Postgres based apps as possible.

**Comment by vitaly-t** [comment]
@voxpelli Thank you! :+1:

**Comment by JaxCavalera** [comment]
Hi guys sorry I didn't get back to you in time, thank you for confirming this and looking into the situation further on my behalf.  I'll go with the advise provided and should there be any problems, I'll contact the correct people regarding.
