### ISSUE TITLE
How do I handle this scenario? If a row hasn't been updated in the last 7 days, do an update. Else do an insert.

### ISSUE THREAD

**Issue by iamsim** [vitaly-t/pg-promise#701]
I have a scenario where I need to bulk update a table with 10000 rows only if a particular row is not updated in last 7 days. If it has been updated in last 7 days, need to do an insert. This is done based on a non-primary key column.

Example - Consider the table
`Human(Id, Name, Weight, UpdatedDate)`
I need to update the value of weight only if the UpdatedDate is not in the last 7 days.
If not, I have to insert the values.
This operation has to be done on bulk for around 10000 rows.

This is not an Issue, its a question. 
Thanks in advance!

**Comment by iamsim** [comment]
Repeated

**Comment by vitaly-t** [comment]
I'm not sure if the solution in your case would require any `pg-promise`-related specific, or if you require something that's more SQL-specific. Because you do not explain where the actual problem is.

I suggest you may find better help publishing such question on StackOverflow, while providing more details.

**Comment by iamsim** [comment]
Thank you for your response. :)
