### ISSUE TITLE
IConnected.done doesn't return Promise

### ISSUE THREAD

**Issue by borissuska** [vitaly-t/pg-promise#782]
### Expected behavior

```
const pgp: IMain = pgPromise(initOptions);
const db: IDatabase<any> = pgp(/* options */);

// direct connection
const conn: IConnected<any, any> = await db.connect({ direct: true });

// conn.query etc.

await conn.done(); <-- expected that IConnected.done returns Promise<void>
```

### Actual behavior

`IConnected.done` returns void

### Environment

* Version of pg-promise: 10.9.5
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: v14.15.1

Underlaying library node-postgres [expect callback](https://github.com/brianc/node-postgres/blob/3dc79b605c9802e67a4263c95e6d4442c1c07ff1/packages/pg/lib/client.js#L580) when ending connection or returns Promise if callback is falsy. The promise is ignored here https://github.com/vitaly-t/pg-promise/blob/1f6b9e719cc57d3facca9f4c2b05018c31cea605/lib/connect.js#L92

**Comment by vitaly-t** [comment]
Originally, the underlying driver did not return any Promise. And after it was added, I tried to find any practical example of using it, but could not, and so that's why I did not update the library for it.

Do you have a practical use case where that Promise is of any benefit? If so, then include it with the issue.

**Comment by vitaly-t** [comment]
Added in [v10.10.1](https://github.com/vitaly-t/pg-promise/releases/tag/10.10.1), to return `Promise`, specifically for direct connections.
