### ISSUE TITLE
Connection pool is not working as expected

### ISSUE THREAD

**Issue by AlandSleman** [vitaly-t/pg-promise#824]
### Actual behavior
I'm trying to implement connection pooling in pg-promise, there is nothing in the docs explaining how it works,i've looked all over stackoverflow too this is the best i've found [https://stackoverflow.com/questions/43250582/connection-pool-using-pg-promise](https://stackoverflow.com/questions/43250582/connection-pool-using-pg-promise)
still doesnt give any explanation on how to actually implement connection pooling so i've figured out its enabled by default but it's not!
 i have an api which is connected to a postgres DB when i make a lot of requests to it the connection jumps instantly reaching the limit(20).
i think it's supposed to only use one connection when you use connection pooling?
so this means the app will slow down if more than 20 users use it at the same time?
checking in pg-admin via: select * from pg_stat_activity;

what can i do to improve this?thanks for answering.
### Steps to reproduce
i'm using this example code:
[https://github.com/vitaly-t/pg-promise/blob/master/examples/query.js](https://github.com/vitaly-t/pg-promise/blob/master/examples/query.js)

### Environment

* Version of pg-promise: 10.11.1
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 16.13.0

**Comment by vitaly-t** [comment]
[It's all documented](https://github.com/brianc/node-postgres/tree/master/packages/pg-pool).

**Comment by AlandSleman** [comment]
> 

you mean i can use pg-pool with pg-promise?

**Comment by vitaly-t** [comment]
> you mean i can use pg-pool with pg-promise?

`pg-pool` is the pool that `pg-promise` uses - check the dependencies.

**Comment by hempels** [comment]
@AlandSleman pg-promise does use connection pooling automatically, by way of pg-pool (as noted by Vitaly.)

It sounds like you're having a fundamental misunderstanding of what connection pool does, though.

> i think it's supposed to only use one connection when you use connection pooling?
That's incorrect. Whatever the pool limit is set at (if you haven't overridden that setting then it will be the default) a new client will be connected each time a query is executed and there is not an idle client to use. If there is an idle client, then it will reuse the existing connection.

Once the pool limit has been reached for number of clients and there are no idle clients, the next query will go into a queue. As soon as a client becomes idle again, the first waiting query will be executed on it.

> so this means the app will slow down if more than 20 users use it at the same time?
Potentially yes, assuming the pool limit is set to 20. You can increase that limit via the `poolSize` connection string/object setting. However, be aware that postgres is extremely sensitive to high connection counts. It is easy to get into a situation where your app runs slow because there are too many active sessions. The main benefit of pooling is that it allows you to limit the number of concurrent queries so the database can operate at peek performance. What that number is depends entirely on your specific situation.
