### ISSUE TITLE
How does one listen to NOTICE/WARN ?

### ISSUE THREAD

**Issue by ceymard** [vitaly-t/pg-promise#83]
How can I know what statements my request my have generated ? There is a message canal usable in PGAdmin, I'm just wondering how I could access it using pg-promise.

**Comment by vitaly-t** [comment]
One can do this in 3 ways:

* Event [query](https://github.com/vitaly-t/pg-promise#query)
* Use [pg-monitor](https://github.com/vitaly-t/pg-monitor), which does a comprehensive event logging
* If you just want to check one particular query, you can call `pgp.as.format`, which is what the library uses to format queries.

**Comment by ceymard** [comment]
Ah found a way ; using event.client.on('notice', ...)

For future people who would be wondering ;

```javascript
require('pg-promise')({
   /* ... */
  query: function (event) {
    event.client.on('notice', function (notice) { console.log(notice) })
  }
}
```

Is it possible to have the notice generated by one particular query ? Using the above code attaches a listener every time I make a query to seemingly the same client object...

I do not see how pgp.as.format can help though...

As for pg-monitor, it looks like it is a command line tool which is no use for me since I actually want to handle the notice in my application (and thus send them to a client, etc..)

**Comment by vitaly-t** [comment]
>Is it possible to have the notice generated by one particular query ? 

What kind of notice are you talking about? You asked about a notice with the query details, and event `query` gives you all that detail.

This is a very unusual idea:
```js
event.client.on('notice', function (notice) { console.log(notice) })
```

I'm not sure what is you are trying to get the notice of...

**Comment by ceymard** [comment]
I use plv8, with which I use the function `plv8.elog(NOTICE, 'my message')`

It is very helpful to me as I use it to keep track of what's happening if very long running functions (30 minute update processes, some whacky algorithms that run entirely inside the database, etc..)

I am thus interested in seeing messages generated by a particular query (like `SELECT my_func()` which could produce a couple hundred of logs over the course of a long time). As the functions are called by a nodejs server and not manually inside pgadmin, I still am looking for a way to get those logs and do stuff with it.

**Comment by vitaly-t** [comment]
Ok, I'm not sure how that really works under the hood. How did you set up the listeners before - on the library level or on the connection level?

This library uses the connection pool provided by node-postgres.

**Comment by vitaly-t** [comment]
I remember somebody else tried to do something similar: https://github.com/mfrasca/ghini/blob/e1404e8c3e1392c32813b2d813bfd43866de39b4/web.js

You see, the event system in node-postgres works against its own concept of the connection pool, that's why if you want to user the old listeners, you'd have to connect to it using the old style.

**Comment by ceymard** [comment]
Ah yes, they're working with pg's pub/sub implementation.

Does this mean that they're bypassing the pool ? Are clients created in this way limited to one query at a time (I would expect it to be the case) ?

**Comment by vitaly-t** [comment]
Exactly, they have to bypass the pool, because the listeners are supposed to be static, while the pool is dynamic.

**Comment by jmealo** [comment]
@ceymard: If you're not afraid of abusing the GUC, you can set your ``application_name`` to match up with the user's session/request and then use syslog or otherwise stream your PostgreSQL log and match the log output back to a query/session/request.

(``application_name`` is the only GUC that you can set which is available for logging)

You can use NGINX/OpenResty to assign a random request id to the incoming request and then pass that on to the application name if your goal is unified logging. I use full SQL logging and am able to see the request from front to back including response time.

If you don't find a work around and your use of ``NOTIFY`` and ``LISTEN`` are connection related, you may want to take a look at my project that allows live streaming of database changes in Node or as a standalone service: https://github.com/JarvusInnovations/lapidus

**Comment by ceymard** [comment]
@jmealo and @vitaly-t, thanks for all the input, I'll try to figure out how I want to do it.

I'll probably try to stay clear of the GUC though, seems like a recipe for headaches :)

**Comment by vitaly-t** [comment]
@ceymard thank you!

@ceymard just to keep in mind, fixing your code to a static connection isn't very good, even the author of node-postgres is trying to discourage developers from doing it, stating that the pool is the recommended approach. The global event listeners on another hand - they are awkward.

**Comment by vitaly-t** [comment]
@ceymard , @jmealo 

[Release v.4.3.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.3.4) has some improvements in this area, to simplify the use of connections.

```
// this will use Client from the connection pool:
db.connect()
    .then(function (obj) {
        obj.client.query('LISTEN "watchers"');
        obj.client.on('notification', function (data) {
            console.log(data.payload);
        });
    });
```

```js
// this will create a new Client:
db.connect({direct: true})
    .then(function (obj) {
        obj.client.query('LISTEN "watchers"');
        obj.client.on('notification', function (data) {
            console.log(data.payload);
        });
    });
```

In both cases, you can either call `done()` on `obj` when you want to release the connection, or never, which in this specific case is acceptable.

See the [connect API](http://vitaly-t.github.io/pg-promise/Database.html#.connect) for details.

**Comment by vitaly-t** [comment]
This has been properly documented: [LISTEN / NOTIFY](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#listen--notify)
