### ISSUE TITLE
Request to update the RobustListener example to use async/await

### ISSUE THREAD

**Issue by slidenerd** [vitaly-t/pg-promise#859]
Could you kindly add a section under [RobustListener](https://github.com/vitaly-t/pg-promise/wiki/Robust-Listeners) that also shows how to use async/await to achieve the same? Thank you in advance

**Comment by vitaly-t** [comment]
That example will not benefit from changing the syntax. The opposite, it will be longer, because of the extra `try->catch` sections that would need to be added. Therefore, I do not see the point in this.

If you want to write strictly in `async/await` notation, and do not understand how promises map into those, you should learn more about promises then. That code is not obsolete, it is quite optimum.
