### ISSUE TITLE
ColumnSet does not recognize a table with schema

### ISSUE THREAD

**Issue by robahtou** [vitaly-t/pg-promise#878]
### Expected behavior

```ts
const table = new pgp.helpers.TableName({ table: 'my-table', schema: 'my-schema' });
const cs = new pgp.helpers.ColumnSet(['filter_id', 'name', 'values'], table);

// no error thrown by `cs`
```

### Actual behavior

```ts
const table = new pgp.helpers.TableName({ table: 'my-table', schema: 'my-schema' });
const cs = new pgp.helpers.ColumnSet(['filter_id', 'name', 'values'], table);
  
// error thrown by `cs`
Error: Option "schema" is not recognized.
```

### Steps to reproduce

**RUN**

```ts
const initOptions = {/* initialization options */};
const pgp = require('pg-promise')(initOptions);

const table = new pgp.helpers.TableName({ table: 'my-table', schema: 'my-schema' });
const cs = new pgp.helpers.ColumnSet(['filter_id', 'name', 'values'], table); //<---- error thrown here
```

### Environment

* Version of pg-promise: latest
* OS type (Linux/Windows/Mac): OSX
* Version of Node.js: latest

**Comment by vitaly-t** [comment]
The error is correct, due to incorrect parameter usage. There's just a little discrepancy within the TypeScript declaration that doesn't detect it...

The correct parameter in this case would be like this:

```ts
const cs = new pgp.helpers.ColumnSet(['filter_id', 'name', 'values'], {table});
```

i.e. the table is one of the options supported by the `ColumnSet`.

What you do - pass in the table object like a set of optional parameters, which TypeScript accepts because both have valid `table` property in it. It would be nice to make TypeScript detect the difference somehow. PR-s are welcome! :wink:

**Comment by robahtou** [comment]
wouldn't mind tackling this. can you point me in the right direction to get started?

**Comment by vitaly-t** [comment]
Are you even using the TypeScript? It is not clear from your examples. And if you are, then you have all the relevant references. And if not, then it is better left for someone who knows TypeScript very well ;)

**Comment by robahtou** [comment]
yeah those examples are slimmed down but I'm using typescript with this project.
I'll report back on what I find.  thanks!!

**Comment by vitaly-t** [comment]
It's been more than a month, and starts to look like a dead issue.

**Comment by robahtou** [comment]
yeah   I couldn't figure it out. Closing this out. Thanks again!
