### ISSUE TITLE
Invalid query formatting with 10 or more parameters passed.

### ISSUE THREAD

**Issue by jcristovao** [vitaly-t/pg-promise#9]
The problem is in ```function $query```, it replaces ```$10```, ```$11```, ```$12``` with the value of ```$1```.

Unfortunately, my regular expressions capabilities are not up to solving this quickly.

Your help is appreciated!
Thanks

**Comment by jcristovao** [comment]
Nevermind... it is as easy as going through the array backwards:
```for (var i = values.length - 1 ; i >= 0; i--) {```

Do you want me to send a pull request nevertheless?

**Comment by vitaly-t** [comment]
@jcristovao , well spotted, the problem is there indeed, i'm looking into it right now, will provide an update here soon.

**Comment by vitaly-t** [comment]
@jcristovao, thank you again for finding this issue. The issue has been fixed and new release 0.6.5 is available with the fix now.

It was very interesting to figure out the best approach, and I tried a few. In the end though, I believe I ended up with the simplest one - see it in the code.

Regarding your suggestion about reversing the search loop - this wouldn't help, it could only solve part of the problem. First of all, as a side effect, it would reverse the direction in which errors are being reported during formatting, which would be bad. And it does not solve the issue with longer variable names. Here's an example:

```javascript
pgp.as.format("$111, $222", [1, 2]);
```
If we just reverse the search, we still end up with the output of '1,2' instead of the expected `$111,$222`, i.e. longer names would be ignored, which is incorrect.

The right approach was to search for the variable, and once found - check that it is not immediately followed by a digit, and if it is - continue the search further.

Initially I implemented such search in a function, but in the end replaced it all with `RegEx` for much more elegant solution. The `RegEx` for variable replacement was also changed according to this logic.

I added 8 new tests in file indexSpec.js to cover every single scenario with variable formatting, including one where I generate 1000 variables and replacements, just to show it works now the same with any number of variables.

```javascript
        // test that errors in type conversion are
        // detected and reported from left to right;
        q = pgp.as.format("$1,$2", [{}, {}]);
        expect(q.success).toBe(false);
        expect(q.error).toBe("Cannot convert parameter with index 0");

        // test that once a conversion issue is encountered,
        // the rest of parameters are not verified;
        q = pgp.as.format("$1,$2", [1, {}, 2, 3, 4, 5]);
        expect(q.success).toBe(false);
        expect(q.error).toBe("Cannot convert parameter with index 1");

        // testing with lots of variables;
        var source = "", dest = "", params = [];
        for(var i = 1;i <= 1000;i ++){
            source += '$' + i;
            dest += i;
            params.push(i);
        }
        q = pgp.as.format(source, params);
        expect(q.success).toBe(true);
        expect(q.query).toBe(dest);

        // testing various cases with many variables:
        // - variables next to each other;
        // - variables not defined;
        // - variables are repeated;
        // - long variable names present;
        q = pgp.as.format("$1$2,$3,$4,$5,$6,$7,$8,$9,$10$11,$12,$13,$14,$15,$1,$3", [1, 2, 'C', 'DDD', 'E', 'F', 'G', 'H', 'I', 88, 99, 'LLL']);
        expect(q.success).toBe(true);
        expect(q.query).toBe("12,'C','DDD','E','F','G','H','I',8899,'LLL',$13,$14,$15,1,'C'");

        // test that $1 variable isn't confused with $12;
        q = pgp.as.format("$12", 123);
        expect(q.success).toBe(false);
        expect(q.error).toBe("No variable found in the query to replace with the passed value.");

        // test that $1 variable isn't confused with $112
        q = pgp.as.format("$112", 123);
        expect(q.success).toBe(false);
        expect(q.error).toBe("No variable found in the query to replace with the passed value.");

        // test that variable names are not confused for longer ones;
        q = pgp.as.format("$11, $1, $111, $1", 123);
        expect(q.success).toBe(true);
        expect(q.query).toBe("$11, 123, $111, 123");

        // test that variable names are not confused for longer ones,
        // even when they are right next to each other;
        q = pgp.as.format("$11$1$111$1", 123);
        expect(q.success).toBe(true);
        expect(q.query).toBe("$11123$111123");
```

**Comment by vitaly-t** [comment]
UPDATE: I'm working in a breaking change for the way `as.format` works by default, hence the few commits so far, more coming.

Basically, the way `as.format` works was derived from the fact that initially this was only used internally by the library, but since it became available externally, it isn't very logical that the method returns an object with the result. What it will do after the change instead - throw an error whenever something is wrong with the formatting request, and it will require optional `se` - `suppress errors` flag, as the third parameter to return an object as before, to remain compatible with its internal usage, and give the end user more control over how to handle errors in query formatting.

**Comment by vitaly-t** [comment]
0.7.0. has been released, with a small breaking change as described.

**Comment by vitaly-t** [comment]
@jcristovao 
You might like the new support for [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters) even better ;)

**Comment by jcristovao** [comment]
Eh eh, thanks :) It might come handy indeed!

**Comment by vitaly-t** [comment]
@jcristovao Unrelated to this, but if you liked this library, I really appreciate if you can give me a feedback on this small addition: [pg-monitor](https://github.com/vitaly-t/pg-monitor)
