### ISSUE TITLE
dangerous example?

### ISSUE THREAD

**Issue by WestleyArgentum** [vitaly-t/pg-promise#93]
I'm probably totally wrong here, but I think one of the examples in the docs drops + creates a table asynchronously in a dangerous way...

The example:
```
db.tx(function (t) {
    // t = this;
    var queries = [
        this.none("drop table users;"),
        this.none("create table users(id serial not null, name text not null)")
    ];
    for (var i = 1; i <= 100; i++) {
        queries.push(this.none("insert into users(name) values($1)", "name-" + i));
    }
    queries.push(
        this.tx(function (t1) {
            // t1 = this != t;
            return this.tx(function (t2) {
                // t2 = this != t1 != t;
                return this.one("select count(*) from users");
            });
        }));
    return this.batch(queries);
})
    .then(function (data) {
        console.log(data); // printing transaction result;
    })
    .catch(function (error) {
        console.log(error); // printing the error;
    });
```

Will `this.batch(queries);` run them all at the same time in parallel? So won't this mean that sometimes the table is dropped and then created and sometimes it's created and then dropped?

**Comment by vitaly-t** [comment]
Node.js parallelism works through IO. Other than that Node.js itself is synchronous.

Translated into the logic of the given example, even though we do not chain the promises, they cannot jump the sequence because they are executed within a transaction, while any transaction executes against a single IO channel, so the sequence is enforced there.

But if it gives you more confidence, you can always promise-chain those requests, though it won't change the outcome.
