### ISSUE TITLE
csv.as with raw - vulnerable?

### ISSUE THREAD

**Issue by pkwnz** [vitaly-t/pg-promise#96]
Hi,

thanks for the great library. Question: 

in an example in the docs we have, query("...WHERE id IN($1^)", pgp.as.csv([1,2,3,4])); 

this looks great because it converts the string in the right way. But if we have a slightly different use case with an array of strings (or mixed types) and this contains external input, it seems on the face of it that this would now be vulnerable to injection attack. Is that correct? Or would the csv() function escape any funny business and protect us in this case?

Thanks again!

**Comment by vitaly-t** [comment]
Method [as.csv](http://vitaly-t.github.io/pg-promise/formatting.html#.csv) escapes all the data correctly, according to its type. So no, it is not vulnerable in any way.

Also note [the alternative syntax since version 3.2.1](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#where-col-in-values).
